#!/bin/sh
# prerm script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
        update-alternatives --remove ssh-askpass /usr/bin/lxqt-openssh-askpass
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
